### ISSUE TITLE
automatic generated git-patch of the railsdiff

### ISSUE THREAD

**Issue by neumayr** [railsdiff/api#4]
Hey! First of all, a big thank you for RailsDiff! 🤓 
It's used as a reference for working and side projects of mine.

The lesser known part is definitely the RailsDiff API Interface: 
e.g. http://api.railsdiff.org/v5.1.3/v5.1.4 outputs the diff, for the frontend.

Would it be possible to automatically generate a `git-apply` / `patch` 
of the full changeset and per file? A bonus with a short notice in the readme.

Maybe some `.diff` / `.patch` urls like github does it with: 
:octocat: https://github.com/blog/967-github-secrets#diff-patch

**Comment by jswanner** [comment]
@neumayr, thanks for the question and the support.

> Would it be possible to automatically generate a git-patch / patch of the full changeset

As you pointed out, that is the response from API.

> Maybe some .diff / .patch urls

It's not really necessary to add a `.diff` extension to the URL, as it already matches what GitHub responds with for `.diff` requests. GitHub's `.patch` URLs respond with a slightly different format, intended to be used with `git am`.

As it stands right now, you can apply the diff that the API responds with using the `git apply` or `patch` utilities. What is probably tripping you up is that the diffs have a file prefix of `generated/<tag-name>/`, that is what the `-p<n>` flags to those utilities are for. Try the following:

```shell
curl -s "http://api.railsdiff.org/v5.1.4/v5.2.0.beta2" | git apply -p2 --reject -
```

Or:

```shell
curl -s "http://api.railsdiff.org/v5.1.4/v5.2.0.beta2" | patch -p2
```

You'll run into problems with any files you have modified since creating them with `rails new`, which makes the whole process much less useful.

> Would it be possible to automatically generate a git-patch / patch [...] per file?

I've thought about adding an API endpoint for generating a diff for a specific file (e.g. http://api.railsdiff.org/v5.1.4/v5.2.0.beta2/Gemfile). Kind of by accident, it already works for files in the root directory (like the previous example), just not nested files.

Here again, `git apply` has an option for this already: `--include`.

```shell
curl -s "http://api.railsdiff.org/v5.1.4/v5.2.0.beta2" | git apply -p2 --include=Gemfile -
```

But again, it only really works for files that you have not modified, and if that's the case Rails provides `rails app:update` (or `rake app:update`) which can pretty much do the same thing.
